/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HbrModal } from "@harbor/elements/dist/types/components/modal/modal";
export namespace Components {
    interface MdButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MdModal {
        /**
          * Hide the modal
         */
        "hide": () => Promise<void>;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * Modal element
         */
        "modal": HbrModal | undefined;
        /**
          * Indicates whether or not the modal is open. You can use this in lieu of the show/hide methods.
         */
        "open": boolean;
        /**
          * Shows the modal
         */
        "show": () => Promise<void>;
    }
}
declare global {
    interface HTMLMdButtonElement extends Components.MdButton, HTMLStencilElement {
    }
    var HTMLMdButtonElement: {
        prototype: HTMLMdButtonElement;
        new (): HTMLMdButtonElement;
    };
    interface HTMLMdModalElement extends Components.MdModal, HTMLStencilElement {
    }
    var HTMLMdModalElement: {
        prototype: HTMLMdModalElement;
        new (): HTMLMdModalElement;
    };
    interface HTMLElementTagNameMap {
        "md-button": HTMLMdButtonElement;
        "md-modal": HTMLMdModalElement;
    }
}
declare namespace LocalJSX {
    interface MdButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MdModal {
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * Modal element
         */
        "modal"?: HbrModal | undefined;
        /**
          * Indicates whether or not the modal is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "md-button": MdButton;
        "md-modal": MdModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "md-button": LocalJSX.MdButton & JSXBase.HTMLAttributes<HTMLMdButtonElement>;
            "md-modal": LocalJSX.MdModal & JSXBase.HTMLAttributes<HTMLMdModalElement>;
        }
    }
}
